PizzaInventory/Models/ErrorViewModel.cs
namespace PizzaInventory.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

PizzaInventory/Models/InventoryItem.cs
using System.Transactions;

namespace PizzaInventory.Models
{
    public class InventoryItem
    // This is the InventoryItem Model. This contains all application business logic, validation logic,
    // and database access logic that pertains to InventoryItem.
    {
        #region properties 
        //class properties corresponding to InventoryItem column names:
        public int InventoryID { get; set; }
        public string Name { get; set; }

        public double Price { get; set; }
        public int Inventory_TypeID { get; set; }
        public string CountUnit { get; set; }
        public string OrderUnit { get; set; }
        public int CountUnitPerOrderUnit { get; set; }
        public int AmtOnHand { get; set; }
        public int StartingAmt { get; set; }
        public int QuantityDelivered { get; set; }
        public int BeginningAmt { get; set; }
        public int EndingAmt { get; set; }
        public int AmtUsed { get; set; }
        #endregion
    }
}

PizzaInventory/Models/InventoryItems.cs
using System.Transactions;

namespace PizzaInventory.Models
{
    public class InventoryItems
    // This is the InventoryItems Model. This contains all application business logic, validation logic,
    // and database access logic that pertains to InventoryItems.
    {
        #region properties 
        //class properties corresponding to InventoryItems column names:
        public int InventoryID { get; set; }
        public string Name { get; set; }

        public double Price { get; set; }
        public int Inventory_TypeID { get; set; }
        public string CountUnit { get; set; }
        public double CountUnitQuantity { get; set; }
        public string OrderUnit { get; set; }
        public double OrderUnitQuantity { get; set; }
        public double CountUnitPerOrderUnit { get; set; }
        public double AmtOnHand { get; set; }
        public double StartingAmt { get; set; }
        public double QuantityDelivered { get; set; }
        public double BeginningAmt { get; set; }
        public double EndingAmt { get; set; }
        public double AmtUsed { get; set; }
        public int Order { get; set; }
        public int SuggestedOrder { get; set; }
        public double Yield { get; set; }
        
        public double margin { get; set; }

        #endregion

    }
}

PizzaInventory/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using PizzaInventory.Models;

namespace PizzaInventory.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

PizzaInventory/Controllers/InventoryItemsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using PizzaInventory.Models;

namespace PizzaInventory.Controllers
{
    public class InventoryItemsController : Controller
    {

        private readonly IInventoryItemsRepository repo;

        public InventoryItemsController(IInventoryItemsRepository repo)
        {
            this.repo = repo;
        }


        public IActionResult Index()
        {
            var inventoryItems = repo.GetAllInventoryItems();
            return View(inventoryItems);
        }

        public IActionResult ViewInventoryItem(int id)
        {
            var inventoryItem = repo.GetInventoryItem(id);
            return View(inventoryItem);
        }

        public IActionResult CountInventory() 
        {
            var inventoryItems = repo.GetAllInventoryItems();
            return View(inventoryItems);
        }

        public IActionResult BulkUpdateInventoryItems(IEnumerable<InventoryItems> inventoryItems)
        {
            repo.BulkCountInventory(inventoryItems);

            return RedirectToAction("CountInventory");
        }

        //public IActionResult FoodOrder(IEnumerable<InventoryItems> inventoryItems)
        //{
        //    repo.FoodOrder(inventoryItems);
        //    return View(inventoryItems);
        //}
    }
}

PizzaInventory/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

PizzaInventory/Views/InventoryItems/CountInventory.cshtml
@model IEnumerable<InventoryItems>



<h2>Countsheet</h2>

@using (Html.BeginForm("BulkUpdateInventoryItems", "InventoryItems", "Post"))
{
    <table class="table table-bordered table-striped table-sm table-hover">
        <tr>
            <th>Name</th>
            <th>Amount On Hand</th>
            <th>Enter Your Count Here:</th>

        </tr>

        @{
            var count = 0;
        }
        @foreach (var item in @Model)
        {
            <tr>
                <td>@item.Name</td> 
                <td>@item.AmtOnHand @item.CountUnit</td>
                <td>
                    <label asp-for="@item.Name" class="control-label">@item.OrderUnit</label>
                    <input name="[@count].InventoryID" type="hidden" value="@item.InventoryID" />
                    <input type="number" step="0.01" name="[@count].OrderUnitQuantity" class="form-control" value="" />
                    

                    <label asp-for="@item.Name" class="control-label">@item.CountUnit</label>
                    <input name="[@count].InventoryID" type="hidden" value="@item.InventoryID" />
                    <input type="number" step="0.01" name="[@count].CountUnitQuantity" class="form-control" value="" />
                </td>   
            </tr>
            count++;
        }

    </table>
    <input type="submit" value="Submit Inventory Count" class="btn btn-primary" />
    
}

PizzaInventory/Views/InventoryItems/Index.cshtml
<!-- This is a Razor View file (.cshtml) that allows us to use C# code with html code using the at symbol -->

<!-- This represents the data model that we will eventually pass to our view stored in variable "at model" -->
@model IEnumerable<InventoryItems>


<!-- The following html code maps out our main inventory items page (index.cshtml). It contains a page header (<h2>)
     followed by a table with a row (<tr>) of table headers (<th>) representing the class properties of our inventory
     items model. Then we use a foreach loop to create rows for each inventory item
-->
<h2>Inventory Items</h2>
<table class="table table-bordered table-striped table-sm table-hover">
    <tr>
        <th>Inventory ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Inventory Type</th>
        <th>Amount On Hand</th>
    </tr>

    @foreach (var item in @Model)
    {
        <tr>
            <td>@item.InventoryID</td>
            <td><a href=/InventoryItems/ViewInventoryItem/@item.InventoryID>@item.Name</a></td> <!--embeds link to ViewInventoryItem in Name-->
            <td>$@item.Price</td>
            <td>@item.Inventory_TypeID</td>
            <td>@item.AmtOnHand @item.CountUnit</td>
        </tr>
    }

</table>

PizzaInventory/Views/InventoryItems/ViewInventoryItem.cshtml
<!-- This is a Razor View file (.cshtml) that allows us to use C# code with html code using the at symbol -->

<!-- This represents the data model that we will eventually pass to our view stored in variable "at model" -->
@model InventoryItems

<h3>@Model.Name Information</h3>

<table class="table">
    <tr>
        <th>Inventory ID</th>
        <th>Name</th>
        <th>Price</th>
        <th>Inventory Type</th>
        <th>Count Unit</th>
        <th>Order Unit</th>
        <th>Count Unit per Order Unit</th>
        <th>Amount on Hand</th>
        <th>Starting Amount</th>
        <th>Quantity Delivered</th>
        <th>Ending Amount</th>
        <th>Amount Used</th>
    </tr>
    <tr>
        <td>@Model.InventoryID</td>
        <td>@Model.Name</td>
        <td>$@Model.Price</td>
        <td>@Model.Inventory_TypeID</td>
        <td>@Model.CountUnit</td>
        <td>@Model.OrderUnit</td>
        <td>@Model.CountUnitPerOrderUnit</td>
        <td>@Model.AmtOnHand @Model.CountUnit</td>
        <td>@Model.StartingAmt</td>
        <td>@Model.QuantityDelivered</td>
        <td>@Model.EndingAmt</td>
        <td>@Model.AmtUsed</td>
    </tr>
</table>

PizzaInventory/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - PizzaInventory</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/PizzaInventory.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">PizzaInventory</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="InventoryItems" asp-action="Index">View Inventory</a>
                        </li>
                        <li class="nav-item">
							<a class="nav-link text-dark" asp-area="" asp-controller="InventoryItems" asp-action="CountInventory">Count Inventory</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - PizzaInventory - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>